#!/usr/bin/env bash
set -euo pipefail

# O3 (0.5.0): origin-state.json carries gates{passed,total}, completedNodes,
# per-status taskCounts, and writer provenance (0.4.0 emitted none — console
# summary fields were null by construction). STATUS.md states its provenance.

ENGINE_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

fail() { echo "FAIL: $*" >&2; exit 1; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
root="$tmp/repo"
mkdir -p "$root/docs/orchestration/tasks" "$root/docs/orchestration/gates" \
  "$root/docs/orchestration/packets/imported" "$root/.gluerun-state/inbox" \
  "$root/.gluerun-state/leases"
git -C "$root" init -q
git -C "$root" checkout -q -b target
git -C "$root" -c user.email=t@t -c user.name=t commit -q --allow-empty -m init

cat >"$root/docs/orchestration/dag.v0.json" <<'EOF'
{
  "schema": "gluerun.orchestration.dag.v0",
  "nodes": [
    { "id": "a", "stage": "S0", "area": "core", "layer": "x", "kind": "contract", "dependsOn": [], "requiredCompletion": "done" },
    { "id": "b", "stage": "S1", "area": "core", "layer": "x", "kind": "contract", "dependsOn": ["a"], "requiredCompletion": "done" }
  ]
}
EOF
cat >"$root/docs/orchestration/gates/a.gate-result.json" <<'EOF'
{"schema":"gluerun.orchestration.gate-result.v0","node":"a","status":"passed","authoritative":true,"evidenceClass":"grandfathered","evidence":[{"kind":"source-path","ref":"x"}],"decidedBy":"t","recordedAt":"2026-06-01T00:00:00Z"}
EOF
for spec in "TASK-0001:ready" "TASK-0002:integrated" "TASK-0003:blocked"; do
  id="${spec%%:*}"; st="${spec##*:}"
  printf '# %s: t\n\nStatus: %s\nArea: core\nDispatch mode: canonical\n\n## Objective\n\nx.\n\n## Scope\n\nOwned files:\n\n- `src/%s.ts`\n' \
    "$id" "$st" "$id" >"$root/docs/orchestration/tasks/$id.md"
done

run_lib() {
  env GLUERUN_ROOT="$root" GLUERUN_STATE_DIR="$root/.gluerun-state" \
    GLUERUN_ORCH_DIR="$root/docs/orchestration" GLUERUN_TASKS_DIR="$root/docs/orchestration/tasks" \
    GLUERUN_LEASES_DIR="$root/.gluerun-state/leases" GLUERUN_INBOX_DIR="$root/.gluerun-state/inbox" \
    GLUERUN_WORKTREES_DIR="$root/.worktrees" \
    GLUERUN_EVENTS_FILE="$root/.gluerun-state/events.ndjson" GLUERUN_TARGET_BRANCH=target \
    bash -c "source '$ENGINE_HOME/engine/lib.sh'; $1"
}

run_lib "gluerun_write_origin_state RUN-test"
python3 - "$root/.gluerun-state/origin-state.json" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
assert d["gates"] == {"passed": 1, "total": 2}, d["gates"]
assert d["completedNodes"] == ["a"], d["completedNodes"]
assert d["taskCounts"] == {"ready": 1, "integrated": 1, "blocked": 1}, d["taskCounts"]
assert isinstance(d["generatedByPid"], int)
assert d["generatedByEntry"] == "reconcile"
PY

run_lib "gluerun_write_status 7 'fixture note'"
grep -q "Generated by: reconcile iteration 7" "$root/.gluerun-state/STATUS.md" \
  || fail "STATUS.md provenance line missing"
grep -q "may be stale while the loop idles" "$root/.gluerun-state/STATUS.md" \
  || fail "STATUS.md staleness note missing"

echo "PASS: test-origin-state"
